---
# tasks file for roles/launch_proxy
# tasks file for roles/launch_proxy
- name: Launch HTTP server container
  docker_container:
    name: http_server
    image: michelenga9/tp-devops-httpd
    ports:
      - "80:80"
    networks:
      - name: my-network
    restart_policy: always
